version: '3'
services:
  db:
    restart: always
    networks:
      default:
  app:
    restart: always
    networks:
      default:
        ipv4_address: 172.20.0.3
networks:
  default:
    ipam:
      config:
        - subnet: 172.20.0.0/16
