version: '3'
services:
  db:
    image: postgres:alpine
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=7hPQdVB5K18Fp0Ji
      - TZ=Asia/Shanghai
  app:
    image: nextcloud:fpm
    volumes:
      - nextcloud:/var/www/html
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=7hPQdVB5K18Fp0Ji
      - POSTGRES_HOST=db
      - TZ=Asia/Shanghai
    depends_on:
      - db
  web:
    image: nginx
    links:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    volumes_from:
      - app
    depends_on:
      - app
volumes:
  nextcloud:
  db: